name: Institutional CI

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Deep Genuine Verification
        run: |
          python scripts/deep_genuine_verification.py

      - name: Run Quick Tests
        run: |
          python scripts/final_github_test.py

name: CI

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run contamination scanner
        run: |
          python scripts/check_no_mocks.py

      - name: Run tests
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: '1'
        run: |
          pytest -q
