name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run contamination scanner
        run: |
          python scripts/check_no_mocks.py

      - name: Run tests
        env:
          POLYGON_API_KEY: ${{HVaxVBqrpmumsZ10foKKkwtyMyPLs5_O}}
        run: |
          pytest -q
